name: CI/CD Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  hello:
     name: Hello job
     runs-on: ubuntu-latest
     steps:
       - run: echo "Hello"
